# Generated by Django 4.1.3 on 2022-12-04 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0004_alter_bloodmeasurement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Birthday',
            field=models.DateField(default=datetime.datetime(2022, 12, 5, 1, 13, 9, 712861)),
        ),
    ]
